"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

import type { CreateEntryPayload, Game, User } from "@/lib/api";
import { createEntry, createGame } from "@/lib/api";
import {
  getTeamByStadium,
  KBO_STADIUMS,
  KBO_TEAM_NAMES,
  normalizeStadiumName,
  normalizeTeamName,
} from "@/lib/kbo";
import { InlineState } from "@/components/inline-state";

type CreateEntryFormProps = {
  users: User[];
  games: Game[];
  initialError?: string | null;
};

type MissionDraft = {
  title: string;
  is_completed: boolean;
};

const PRESET_MISSIONS = [
  "응원 포인트 남기기",
  "기억에 남는 장면 체크",
  "오늘의 MVP 떠올리기",
  "경기장 음식 기록하기",
  "좌석 시야 기록하기",
] as const;

function toDateInputValue(value?: string) {
  if (!value) {
    return new Date().toISOString().slice(0, 10);
  }

  return new Date(value).toISOString().slice(0, 10);
}

function toNullableScore(value: string) {
  if (value.trim().length === 0) {
    return null;
  }

  const score = Number(value);
  return Number.isNaN(score) ? null : score;
}

export function CreateEntryForm({
  users,
  games,
  initialError,
}: CreateEntryFormProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const initialDate = searchParams.get("date");
  const [userId] = useState<number | "">(users[0]?.id ?? "");
  const [gameId, setGameId] = useState<number | "">("");
  const [selectedDate, setSelectedDate] = useState(initialDate ?? toDateInputValue());
  const [selectedStadium, setSelectedStadium] = useState("");
  const [selectedHomeTeam, setSelectedHomeTeam] = useState("");
  const [selectedAwayTeam, setSelectedAwayTeam] = useState("");
  const [watchedTeam, setWatchedTeam] = useState("");
  const [memo, setMemo] = useState("");
  const [autoGenerateDiary, setAutoGenerateDiary] = useState(true);
  const [weather, setWeather] = useState("");
  const [seat, setSeat] = useState("");
  const [companion, setCompanion] = useState("");
  const [displayHomeScore, setDisplayHomeScore] = useState("0");
  const [displayAwayScore, setDisplayAwayScore] = useState("0");
  const [missions, setMissions] = useState<MissionDraft[]>([
    { title: "응원 포인트 남기기", is_completed: true },
    { title: "기억에 남는 장면 체크", is_completed: false },
  ]);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(initialError ?? null);

  const selectedGame = useMemo(
    () => games.find((game) => game.id === gameId) ?? null,
    [gameId, games],
  );
  const stadiumOptions = useMemo(
    () =>
      Array.from(
        new Set([
          ...KBO_STADIUMS,
          ...games
            .map((game) => game.stadium)
            .map((stadium) => normalizeStadiumName(stadium))
            .filter(Boolean),
        ]),
      ),
    [games],
  );
  const teamOptions = useMemo(
    () =>
      Array.from(
        new Set([
          ...KBO_TEAM_NAMES,
          ...games.flatMap((game) => [
            normalizeTeamName(game.home_team),
            normalizeTeamName(game.away_team),
          ]),
        ]),
      ),
    [games],
  );

  useEffect(() => {
    if (!selectedHomeTeam || !selectedAwayTeam) {
      setWatchedTeam("");
      return;
    }

    if (watchedTeam !== selectedHomeTeam && watchedTeam !== selectedAwayTeam) {
      setWatchedTeam(selectedHomeTeam);
    }
  }, [selectedAwayTeam, selectedHomeTeam, watchedTeam]);

  useEffect(() => {
    const matchedGame = games.find((game) => {
      const gameDate = toDateInputValue(game.game_date);

      return (
        gameDate === selectedDate &&
        normalizeStadiumName(game.stadium) === selectedStadium &&
        normalizeTeamName(game.home_team) === selectedHomeTeam &&
        normalizeTeamName(game.away_team) === selectedAwayTeam
      );
    });

    if (!matchedGame) {
      setGameId("");
      return;
    }

    setGameId(matchedGame.id);
    setDisplayHomeScore(String(matchedGame.home_score ?? 0));
    setDisplayAwayScore(String(matchedGame.away_score ?? 0));
  }, [games, selectedAwayTeam, selectedDate, selectedHomeTeam, selectedStadium]);

  const canSubmit = Boolean(
    userId &&
      selectedDate &&
      selectedStadium &&
      selectedHomeTeam &&
      selectedAwayTeam &&
      selectedHomeTeam !== selectedAwayTeam &&
      watchedTeam &&
      (autoGenerateDiary || memo.trim().length > 0),
  );
  const homeScore = toNullableScore(displayHomeScore);
  const awayScore = toNullableScore(displayAwayScore);
  const gameUsesSelectedLabels = Boolean(
    selectedGame &&
      selectedGame.stadium === selectedStadium &&
      selectedGame.home_team === selectedHomeTeam &&
      selectedGame.away_team === selectedAwayTeam,
  );
  const scoreChanged = Boolean(
    selectedGame &&
      (selectedGame.home_score !== homeScore || selectedGame.away_score !== awayScore),
  );
  const needsNewGame = !selectedGame || !gameUsesSelectedLabels || scoreChanged;

  const handleStadiumChange = (stadium: string) => {
    const stadiumTeam = getTeamByStadium(stadium);
    setSelectedStadium(stadium);

    if (!stadiumTeam) {
      return;
    }

    setSelectedHomeTeam(stadiumTeam.name);
    if (selectedAwayTeam === stadiumTeam.name) {
      setSelectedAwayTeam(teamOptions.find((team) => team !== stadiumTeam.name) ?? "");
    }
  };

  const updateMission = (
    index: number,
    key: keyof MissionDraft,
    value: string | boolean,
  ) => {
    setMissions((current) =>
      current.map((mission, missionIndex) =>
        missionIndex === index ? { ...mission, [key]: value } : mission,
      ),
    );
  };

  const addMission = () => {
    setMissions((current) => [
      ...current,
      { title: "", is_completed: false },
    ]);
  };

  const addPresetMission = (title: string) => {
    setMissions((current) => {
      if (current.some((mission) => mission.title.trim() === title)) {
        return current;
      }

      return [...current, { title, is_completed: false }];
    });
  };

  const removeMission = (index: number) => {
    setMissions((current) => current.filter((_, missionIndex) => missionIndex !== index));
  };

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!canSubmit || typeof userId !== "number") {
      setSubmitError("날짜, 경기장, 홈팀, 원정팀, 응원 팀을 모두 선택해주세요.");
      return;
    }

    setSubmitting(true);
    setSubmitError(null);

    try {
      let entryGameId = typeof gameId === "number" && !needsNewGame ? gameId : null;

      if (!entryGameId) {
        const createdGame = await createGame({
          game_date: new Date(`${selectedDate}T18:30:00`).toISOString(),
          stadium: selectedStadium,
          home_team: selectedHomeTeam,
          away_team: selectedAwayTeam,
          home_score: homeScore,
          away_score: awayScore,
          status: "기록 완료",
        });

        entryGameId = createdGame.id;
      }

      const payload: CreateEntryPayload = {
        user_id: userId,
        game_id: entryGameId,
        watched_team: watchedTeam,
        memo,
        diary_text: autoGenerateDiary ? null : memo.trim(),
        auto_generate_diary: autoGenerateDiary,
        missions: missions
          .filter((mission) => mission.title.trim().length > 0)
          .map((mission) => ({
            title: mission.title.trim(),
            is_completed: mission.is_completed,
          })),
      };

      const created = await createEntry(payload);
      router.push(`/entries/${created.id}`);
    } catch (error) {
      const message =
        error instanceof Error ? error.message : "기록 저장 중 오류가 발생했습니다.";
      setSubmitError(message);
      setSubmitting(false);
    }
  };

  return (
    <form className="form-card create-form" onSubmit={handleSubmit}>
      <div className="create-form__header">
        <span className="create-form__eyebrow">경기 기록</span>
        <h1>경기 정보를 입력하세요</h1>
        <p>차근차근 적으면 직관 티켓이 완성돼요.</p>
        <button
          aria-label="닫기"
          className="create-form__close"
          type="button"
          onClick={() => router.back()}
        >
          ×
        </button>
      </div>

      <div className="create-form__body">
        {submitError ? (
          <InlineState
            tone="error"
            title="티켓 생성에 실패했어요."
            description={submitError}
          />
        ) : null}

        <section className="create-panel create-panel--step-one create-panel--compact">
          <div className="create-step-card__header">
            <span className="create-step-card__eyebrow">1단계</span>
            <strong>경기 날짜</strong>
          </div>

          <label className="field">
            <span className="create-label">경기 날짜</span>
            <input
              className="create-input"
              type="date"
              value={selectedDate}
              onChange={(event) => setSelectedDate(event.target.value)}
            />
          </label>
        </section>

        <section className="create-panel create-panel--field">
          <div className="create-step-card__header">
            <span className="create-label">경기장</span>
          </div>
          <select
            className="create-input"
            value={selectedStadium}
            onChange={(event) => handleStadiumChange(event.target.value)}
          >
            <option value="">선택하기</option>
            {stadiumOptions.map((stadium) => (
              <option key={stadium} value={stadium}>
                {stadium}
              </option>
            ))}
          </select>
        </section>

        <div className="create-team-grid">
          <section className="create-panel create-panel--home">
            <div className="create-step-card__header">
              <span className="create-label">홈팀</span>
            </div>
            <select
              className="create-input"
              value={selectedHomeTeam}
              onChange={(event) => setSelectedHomeTeam(event.target.value)}
            >
              <option value="">선택하기</option>
              {teamOptions.map((team) => (
                <option key={team} value={team}>
                  {team}
                </option>
              ))}
            </select>
          </section>

          <section className="create-panel create-panel--away">
            <div className="create-step-card__header">
              <span className="create-label">원정팀</span>
            </div>
            <select
              className="create-input"
              value={selectedAwayTeam}
              onChange={(event) => setSelectedAwayTeam(event.target.value)}
            >
              <option value="">선택하기</option>
              {teamOptions.map((team) => (
                <option key={team} value={team}>
                  {team}
                </option>
              ))}
            </select>
          </section>
        </div>

        <section className="create-panel create-panel--score">
          <div className="create-step-card__header">
            <span className="create-label">최종 점수</span>
          </div>

          <div className="create-score-grid">
            <div className="create-score-col">
              <span className="create-score-col__label">홈팀</span>
              <input
                className="create-input create-input--score"
                inputMode="numeric"
                onChange={(event) => setDisplayHomeScore(event.target.value)}
                value={displayHomeScore}
              />
            </div>
            <div className="create-score-col">
              <span className="create-score-col__label">원정팀</span>
              <input
                className="create-input create-input--score"
                inputMode="numeric"
                onChange={(event) => setDisplayAwayScore(event.target.value)}
                value={displayAwayScore}
              />
            </div>
          </div>
        </section>

        <section className="create-panel create-panel--team">
          <div className="create-step-card__header">
            <span className="create-step-card__eyebrow">2단계</span>
            <strong>내가 응원한 팀</strong>
          </div>

          <label className="field">
            <span className="create-label">응원 팀 선택</span>
            <select
              className="create-input"
              value={watchedTeam}
              onChange={(event) => setWatchedTeam(event.target.value)}
            >
              <option value="">선택하기</option>
              {selectedHomeTeam ? (
                <option value={selectedHomeTeam}>{selectedHomeTeam}</option>
              ) : null}
              {selectedAwayTeam ? (
                <option value={selectedAwayTeam}>{selectedAwayTeam}</option>
              ) : null}
            </select>
          </label>
          {selectedHomeTeam === selectedAwayTeam ? (
            <p className="create-form__hint">홈팀과 원정팀은 서로 달라야 해요.</p>
          ) : null}
          {needsNewGame ? (
            <p className="create-form__hint">선택한 조합으로 새 경기 정보를 함께 저장합니다.</p>
          ) : null}
        </section>

        <section className="create-panel create-panel--memo create-panel--diary">
          <div className="create-step-card__header">
            <span className="create-step-card__eyebrow">다이어리</span>
            <strong>{autoGenerateDiary ? "AI가 다이어리로 정리해요" : "내가 직접 다이어리를 써요"}</strong>
          </div>

          <div className="create-diary-mode" aria-label="다이어리 작성 방식">
            <button
              className={autoGenerateDiary ? "is-active" : ""}
              type="button"
              onClick={() => setAutoGenerateDiary(true)}
            >
              AI 자동 작성
            </button>
            <button
              className={!autoGenerateDiary ? "is-active" : ""}
              type="button"
              onClick={() => setAutoGenerateDiary(false)}
            >
              직접 쓰기
            </button>
          </div>

          <label className="field">
            <span className="create-label">
              {autoGenerateDiary ? "키워드와 기억나는 장면" : "오늘의 직관 다이어리"}
            </span>
            <textarea
              className="create-input create-textarea"
              rows={5}
              placeholder={
                autoGenerateDiary
                  ? "예: 9회말 응원 미쳤음, 홈런, 친구랑 감, 잠실 분위기 좋았다"
                  : "오늘의 직관을 내 문장으로 자유롭게 적어주세요."
              }
              value={memo}
              onChange={(event) => setMemo(event.target.value)}
            />
          </label>
          <p className="create-form__hint">
            {autoGenerateDiary
              ? "짧게 적어도 경기 정보와 함께 자연스러운 다이어리로 저장돼요."
              : "입력한 문장이 그대로 다이어리에 저장돼요."}
          </p>
        </section>

        <section className="create-panel create-panel--mission">
          <div className="create-step-card__header">
            <span className="create-step-card__eyebrow">선택</span>
            <strong>오늘의 미션</strong>
          </div>

          <div className="create-mission-presets">
            {PRESET_MISSIONS.map((mission) => (
              <button
                className="create-mission-chip"
                key={mission}
                type="button"
                onClick={() => addPresetMission(mission)}
              >
                {mission}
              </button>
            ))}
            <button
              className="create-mission-chip create-mission-chip--ghost"
              type="button"
              onClick={addMission}
            >
              직접 추가
            </button>
          </div>

          <div className="create-mission-list">
            {missions.map((mission, index) => (
              <div className="create-mission-item" key={`${mission.title}-${index}`}>
                <input
                  checked={mission.is_completed}
                  className="create-mission-item__check"
                  type="checkbox"
                  onChange={(event) =>
                    updateMission(index, "is_completed", event.target.checked)
                  }
                />
                <input
                  className="create-input create-mission-item__input"
                  placeholder="예: 응원가 따라 부르기"
                  type="text"
                  value={mission.title}
                  onChange={(event) =>
                    updateMission(index, "title", event.target.value)
                  }
                />
                <button
                  className="create-mission-item__remove"
                  type="button"
                  onClick={() => removeMission(index)}
                >
                  삭제
                </button>
              </div>
            ))}
          </div>
        </section>

        <section className="create-panel create-panel--utility-row">
          <div className="create-step-card__header">
            <span className="create-step-card__eyebrow">선택</span>
            <strong>선택 정보</strong>
          </div>
          <div className="create-utility-grid create-utility-grid--optional">
            <label className="create-utility-card">
              <span className="create-label">날씨</span>
              <select
                className="create-input create-input--compact"
                value={weather}
                onChange={(event) => setWeather(event.target.value)}
              >
                <option value="">선택</option>
                <option value="맑음">맑음</option>
                <option value="흐림">흐림</option>
                <option value="비">비</option>
                <option value="쌀쌀함">쌀쌀함</option>
              </select>
            </label>
            <label className="create-utility-card">
              <span className="create-label">좌석</span>
              <input
                className="create-input create-input--compact"
                placeholder="예: 3루 207"
                value={seat}
                onChange={(event) => setSeat(event.target.value)}
              />
            </label>
            <label className="create-utility-card create-utility-card--wide">
              <span className="create-label">동행인</span>
              <input
                className="create-input create-input--compact"
                placeholder="예: 친구, 가족, 혼자"
                value={companion}
                onChange={(event) => setCompanion(event.target.value)}
              />
            </label>
          </div>
        </section>

        <div className="create-actions">
          <button
            className="button button--ghost create-submit create-submit--cancel"
            type="button"
            onClick={() => router.back()}
          >
            취소
          </button>
          <button
            className="button button--primary create-submit"
            disabled={!canSubmit || submitting}
            type="submit"
          >
            {submitting ? "기록 저장 중..." : "티켓 생성"}
          </button>
        </div>
      </div>
    </form>
  );
}
